// ═══════════════════════════════════════════════════════════════════════
// XuperStream - Live TV Channels
// Fuentes: iptv-org/iptv, m3u.cl, canales públicos colombianos
// ═══════════════════════════════════════════════════════════════════════

export interface LiveTVChannel {
  id: string;
  name: string;
  description: string;
  logo: string;
  url: string;
  category: string;
  language: string;
  country: string;
}

export const LIVE_TV_CHANNELS: LiveTVChannel[] = [
  // ╔═══════════════════════════════════════════════════════════════════╗
  // ║  COLOMBIA - CANALES NACIONALES                                    ║
  // ╚═══════════════════════════════════════════════════════════════════╝
  {
    id: 'senal-colombia',
    name: 'Senal Colombia',
    description: 'Canal público nacional de Colombia. Cultura, educación y entretenimiento para todos los colombianos.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Se%C3%B1al_Colombia_logo.svg/200px-Se%C3%B1al_Colombia_logo.svg.png',
    url: 'https://streaming.rtvc.gov.co/TV_Senal_Colombia_live/smil:live.smil/playlist.m3u8',
    category: 'co-nacional',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'canal-institucional',
    name: 'Canal Institucional',
    description: 'Canal del Estado colombiano. Transmisiones del Congreso, gobierno y eventos oficiales.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Canal_Institucional_%28Colombia%29.svg/200px-Canal_Institucional_%28Colombia%29.svg.png',
    url: 'https://streaming.rtvc.gov.co/TV_CanalInstitucional_live/smil:live.smil/playlist.m3u8',
    category: 'co-nacional',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'canal-congreso',
    name: 'Canal Congreso',
    description: 'Transmisiones en vivo del Congreso de la República de Colombia. Debates y sesiones plenarias.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Congreso_de_Colombia.svg/200px-Congreso_de_Colombia.svg.png',
    url: 'https://cdn.colombiawebs.com/congreso/live.m3u8',
    category: 'co-nacional',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'canal-uno',
    name: 'Canal 1',
    description: 'Primer canal de televisión privada de Colombia. Noticias, entretenimiento y programación variada.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/5/57/Canal_1_2017.png',
    url: 'https://mdstrm.com/live-stream-playlist/5a5e1c2568b1910913db5fe2.m3u8',
    category: 'co-nacional',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'citytv',
    name: 'Citytv',
    description: 'Canal de televisión de Bogotá. Noticias locales, entretenimiento y programación juvenil.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Citytv_logo.svg/200px-Citytv_logo.svg.png',
    url: 'http://181.114.57.246:4000/play/u2H4dIJoRipgGI3A/index.m3u8',
    category: 'co-nacional',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'red-plus',
    name: 'Red+',
    description: 'Canal de noticias y entretenimiento colombiano. Información las 24 horas.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Red_%2B_logo.svg/200px-Red_%2B_logo.svg.png',
    url: 'https://inforedvos.lcdn.claro.net.co/Content/HLS_HLS_DIR/Live/channel(REDMASHDWEB)/master.m3u8',
    category: 'co-nacional',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'canal-tro',
    name: 'Canal TRO',
    description: 'Canal de televisión regional oriental de Colombia. Entretenimiento y cultura local.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Canal_TRO.svg/200px-Canal_TRO.svg.png',
    url: 'https://liveingesta118.cdnmedia.tv/canaltro2live/smil:live.smil/playlist.m3u8',
    category: 'co-nacional',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'canal-capital',
    name: 'Canal Capital',
    description: 'Canal de la capital Bogotá. Noticias, cultura y entretenimiento de la ciudad.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Canal_Capital_%28Bogot%C3%A1%29.svg/200px-Canal_Capital_%28Bogot%C3%A1%29.svg.png',
    url: 'https://mdstrm.com/live-stream-playlist/6952dc88cb62083467eb6ab4.m3u8',
    category: 'co-nacional',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'trece',
    name: 'Canal Trece',
    description: 'Canal 13 de Bogotá. Programación cultural, informativa y de entretenimiento.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Trece_logo.svg/200px-Trece_logo.svg.png',
    url: 'https://liveingesta118.cdnmedia.tv/trecetvlive/smil:rtmp01.smil/playlist.m3u8',
    category: 'co-nacional',
    language: 'es',
    country: 'CO',
  },

  // ╔═══════════════════════════════════════════════════════════════════╗
  // ║  COLOMBIA - CANALES REGIONALES                                    ║
  // ╚═══════════════════════════════════════════════════════════════════╝
  {
    id: 'teleantioquia',
    name: 'Teleantioquia',
    description: 'Canal regional de Antioquia. Noticias, cultura y deportes del departamento.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Teleantioquia_logo.png/200px-Teleantioquia_logo.png',
    url: 'https://liveingesta118.cdnmedia.tv/teleantioquialive/smil:dvrlive.smil/playlist.m3u8',
    category: 'co-regional',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'telemedellin',
    name: 'Telemedellin',
    description: 'Canal de la ciudad de Medellín. Noticias, eventos y cultura paisa.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Telemedell%C3%ADn_logo.svg/200px-Telemedell%C3%ADn_logo.svg.png',
    url: 'https://liveingesta118.cdnmedia.tv/tvtelemedellinlive/smil:rtmp01.smil/playlist.m3u8',
    category: 'co-regional',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'telecaribe',
    name: 'Telecaribe',
    description: 'Canal regional de la Costa Caribe colombiana. Cultura, noticias y entretenimiento.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Telecaribe_logo.png/200px-Telecaribe_logo.png',
    url: 'https://liveingesta118.cdnmedia.tv/telecaribetvlive/smil:rtmp01.smil/playlist.m3u8',
    category: 'co-regional',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'telecaribe-plus',
    name: 'Telecaribe Plus',
    description: 'Señal adicional de Telecaribe con programación complementaria y eventos especiales.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Telecaribe_logo.png/200px-Telecaribe_logo.png',
    url: 'https://liveingesta118.cdnmedia.tv/telecaribetvlive/smil:rtmp02.smil/playlist.m3u8',
    category: 'co-regional',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'telecafe',
    name: 'Telecafe',
    description: 'Canal regional del Eje Cafetero. Noticias, cultura y tradición cafetera colombiana.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Telecafe_logo.png/200px-Telecafe_logo.png',
    url: 'https://liveingesta318.cdnmedia.tv/telecafelive/smil:rtmp01.smil/playlist.m3u8',
    category: 'co-regional',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'telepacifico',
    name: 'Telepacifico',
    description: 'Canal regional del suroccidente colombiano. Noticias y cultura del Valle del Cauca.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Telepac%C3%ADfico_logo.svg/200px-Telepac%C3%ADfico_logo.svg.png',
    url: 'https://play.cdn.enetres.net/6E5C615AA5FF4123ACAF0DAB57B7B8DC021/022/playlist.m3u8',
    category: 'co-regional',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'telebolivar',
    name: 'Telebolivar',
    description: 'Canal regional de Bolívar. Noticias y cultura de la región cartagenera.',
    logo: 'https://i.imgur.com/dYhnVoV.png',
    url: 'https://live20.bozztv.com/akamaissh101/ssh101/telebolivar/playlist.m3u8',
    category: 'co-regional',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'cali-tv',
    name: 'Cali TV',
    description: 'Canal de la ciudad de Santiago de Cali. Noticias, cultura y eventos locales.',
    logo: 'https://i.imgur.com/2312Luq.png',
    url: 'https://5ab772334c39c.streamlock.net/live-calitv/calitv1/playlist.m3u8',
    category: 'co-regional',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'ctv-barranquilla',
    name: 'CTV Barranquilla',
    description: 'Canal comunitario de Barranquilla. Noticias y cultura de la capital atlántica.',
    logo: 'https://i.imgur.com/w35ICn7.png',
    url: 'https://live.ctvbarranquilla.com/live/ctv-4ad31c89f3764bf0980e642bc12fd00a.m3u8',
    category: 'co-regional',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'cosmovision',
    name: 'Cosmovision',
    description: 'Canal cultural de Colombia. Documentales, arte y programación educativa.',
    logo: 'https://i.imgur.com/QlvYfEJ.png',
    url: 'https://videohls2.cosmovision.tv/hls/sd.m3u8',
    category: 'co-regional',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'canal-chd',
    name: 'Canal CHD',
    description: 'Canal de televisión local colombiano con programación variada.',
    logo: 'https://i.imgur.com/cNv1MPs.jpeg',
    url: 'https://vs20.live.opencaster.com/canalchd2025_8d99626c/index.m3u8',
    category: 'co-regional',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'tele-islas',
    name: 'Teleislas',
    description: 'Canal del archipiélago de San Andrés y Providencia. Cultura e información local.',
    logo: 'https://i.imgur.com/aKHGRyk.png',
    url: 'https://5ab772334c39c.streamlock.net/live-teleislas/teleislas/playlist.m3u8',
    category: 'co-regional',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'canal-santa-marta',
    name: 'Canal Santa Marta TV',
    description: 'Canal local de Santa Marta. Noticias, turismo y cultura de la Perla del Caribe.',
    logo: 'https://i.imgur.com/HbWadhJ.png',
    url: 'https://stream.amelbasoluciones.co/live/santamartalive.m3u8',
    category: 'co-regional',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'telesangil',
    name: 'Telesangil',
    description: 'Canal regional del Santander colombiano. Noticias y cultura regional.',
    logo: 'https://i.ibb.co/27Pzdvw/cropped-TELESANGIL-LOGO-1.png',
    url: 'https://live20.bozztv.com/akamaissh101/ssh101/telesangil/playlist.m3u8',
    category: 'co-regional',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'tele-mocoa',
    name: 'Tele Mocoa',
    description: 'Canal local de Mocoa, Putumayo. Noticias y cultura amazónica colombiana.',
    logo: 'https://i.imgur.com/XHtpEfu.png',
    url: 'https://live.amelbatv.co:81/telemocoalive/index.m3u8',
    category: 'co-regional',
    language: 'es',
    country: 'CO',
  },

  // ╔═══════════════════════════════════════════════════════════════════╗
  // ║  COLOMBIA - DEPORTES                                              ║
  // ╚═══════════════════════════════════════════════════════════════════╝
  {
    id: 'win-sports',
    name: 'Win Sports',
    description: 'El canal deportivo de Colombia. Fútbol profesional colombiano, Liga BetPlay y más.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Win_Sports_logo.png/200px-Win_Sports_logo.png',
    url: 'http://190.60.40.34:8001/play/a0ef',
    category: 'co-deportes',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'win-sports-plus',
    name: 'Win+ Futbol',
    description: 'Señal alternativa de Win Sports. Cobertura adicional de partidos y análisis deportivo.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Win_Sports_logo.png/200px-Win_Sports_logo.png',
    url: 'http://190.60.40.34:8001/play/a02r',
    category: 'co-deportes',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'directv-sports',
    name: 'DirecTV Sports',
    description: 'Canal deportivo latinoamericano. Fútbol, tenis, baloncesto y competencias internacionales.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/DirecTV_Sports_Latin_America_%282018%29.png/200px-DirecTV_Sports_Latin_America_%282018%29.png',
    url: 'https://latam-cache-sv2-cdn.latamlive.net/DS1_ENC_LIVE/index.mpd',
    category: 'co-deportes',
    language: 'es',
    country: 'LATAM',
  },
  {
    id: 'red-bull-tv',
    name: 'Red Bull TV',
    description: 'Deportes extremos, aventura y eventos en vivo. Surf, skate, FMX y más.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Red_Bull_TV_logo.svg/200px-Red_Bull_TV_logo.svg.png',
    url: 'https://rbmn-live.akamaized.net/hls/live/2002825/geoRBTV_SPORTS/master.m3u8',
    category: 'co-deportes',
    language: 'es',
    country: 'INTL',
  },
  {
    id: 'real-madrid-tv',
    name: 'Real Madrid TV',
    description: 'Canal oficial del Real Madrid. Entrenamientos, partidos, entrevistas y noticias del club.',
    logo: 'https://upload.wikimedia.org/wikipedia/en/0/0c/Real_Madrid_TV_logo.png',
    url: 'https://rmtv.akamaized.net/hls/live/2043153/rmtv-en/master.m3u8',
    category: 'co-deportes',
    language: 'es',
    country: 'ES',
  },
  {
    id: 'fifa-plus',
    name: 'FIFA+',
    description: 'Plataforma oficial de la FIFA. Partidos en vivo, resúmenes y contenido exclusivo del fútbol mundial.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/FIFA_Plus_logo.svg/200px-FIFA_Plus_logo.svg.png',
    url: 'https://d2hrvno5bw6tg2.cloudfront.net/fifaplus/master.m3u8',
    category: 'co-deportes',
    language: 'es',
    country: 'INTL',
  },

  // ╔═══════════════════════════════════════════════════════════════════╗
  // ║  COLOMBIA - NOTICIAS                                             ║
  // ╚═══════════════════════════════════════════════════════════════════╝
  {
    id: 'canal-pyc',
    name: 'Canal PyC',
    description: 'Canal de noticias y opinión colombiano. Análisis político y actualidad nacional.',
    logo: 'https://i.imgur.com/3qxBDhV.png',
    url: 'https://live20.bozztv.com/akamaissh101/ssh101/pyctelevision/playlist.m3u8',
    category: 'co-noticias',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'blu-radio',
    name: 'Blu Radio',
    description: 'Emisora de radio colombiana con transmisión de TV. Noticias y opinión las 24 horas.',
    logo: 'https://i.imgur.com/w2t8CGT.png',
    url: 'https://mdstrm.com/live-stream-playlist/58d1921a72e2b22e2905e493.m3u8',
    category: 'co-noticias',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'noticiero-90-min',
    name: 'Noticiero 90 Minutos',
    description: 'Noticiero colombiano con amplia cobertura de noticias nacionales e internacionales.',
    logo: 'https://i.imgur.com/ThaRRCN.png',
    url: 'https://play.cdn.enetres.net/621B146D29C541AFB1507809F038F471021/021/playlist.m3u8',
    category: 'co-noticias',
    language: 'es',
    country: 'CO',
  },

  // ╔═══════════════════════════════════════════════════════════════════╗
  // ║  COLOMBIA - MUSICA                                                ║
  // ╚═══════════════════════════════════════════════════════════════════╝
  {
    id: 'la-kalle',
    name: 'La Kalle',
    description: 'Radio y TV musical colombiana. Reggaetón, pop, salsa y los mejores éxitos.',
    logo: 'https://www.tdtparatodos.tv/sites/default/files/la_kalle.png',
    url: 'https://mdstrm.com/live-stream-playlist/58d191f07290fbb058025843.m3u8',
    category: 'co-musica',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'salsa-gorda',
    name: 'Salsa Gorda TV',
    description: 'Canal dedicado a la salsa colombiana y latina. Los mejores artistas y ritmos del Caribe.',
    logo: 'https://i.imgur.com/3IhYd7G.jpg',
    url: 'https://live20.bozztv.com/akamaissh101/ssh101/qMUAZEy/playlist.m3u8',
    category: 'co-musica',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'parranda-vallenata',
    name: 'Parranda Vallenata',
    description: 'Vallenato puro 24/7. Los mejores intérpretes del folclore vallenato colombiano.',
    logo: 'https://i.imgur.com/BzBX7Qx.jpeg',
    url: 'https://backupmaxmedia.hvmultiplay.com/hls/stream3/parrandavallenata.m3u8',
    category: 'co-musica',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'supermusica-tv',
    name: 'Supermusica TV',
    description: 'Canal musical con los mejores videos y conciertos. Pop, rock y música tropical.',
    logo: 'https://i.imgur.com/MiVs42N.jpeg',
    url: 'https://backupmaxmedia.hvmultiplay.com/hls/stream4/supermusica.m3u8',
    category: 'co-musica',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'la-hermandad-salsera',
    name: 'La Hermandad Salsera',
    description: 'La mejor salsa del mundo. Clásicos y nuevos talentos de la salsa latinoamericana.',
    logo: 'https://i.imgur.com/7Wlt6bc.png',
    url: 'https://streamlov.alsolnet.com/hermandadsalsera/live/playlist.m3u8',
    category: 'co-musica',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'vallenato-internacional',
    name: 'Vallenato Internacional',
    description: 'Festival del Vallenato y lo mejor de la música folclórica colombiana en vivo.',
    logo: 'https://i.imgur.com/rVKroNW.png',
    url: 'https://59a564764e2b6.streamlock.net/vallenato/vallenatom/playlist.m3u8',
    category: 'co-musica',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'mas-musica-fm',
    name: 'MasMusica FM',
    description: 'Radio musical con transmisión visual. Éxitos de la música latina y colombiana.',
    logo: 'https://i.imgur.com/tCg7owd.png',
    url: 'https://movil.ejeserver.com/live/masmusica.m3u8',
    category: 'co-musica',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'rumba-tv',
    name: 'Rumba TV',
    description: 'Los mejores videos musicales de reggaetón, salsa, pop latino y más.',
    logo: 'https://i.imgur.com/1v2tKfH.png',
    url: 'https://streamyes.akamaized.net/hls/rumbatv/playlist.m3u8',
    category: 'co-musica',
    language: 'es',
    country: 'CO',
  },

  // ╔═══════════════════════════════════════════════════════════════════╗
  // ║  COLOMBIA - PELICULAS Y SERIES                                    ║
  // ╚═══════════════════════════════════════════════════════════════════╝
  {
    id: 'retro-tv',
    name: 'Retro TV',
    description: 'Series y películas clásicas 24/7. Los mejores programas de la televisión retro.',
    logo: 'https://i.imgur.com/8uXlS0H.png',
    url: 'https://cdn.klowdtv.net/live1/retrotv_720p/playlist.m3u8',
    category: 'co-peliculas',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'accion-247',
    name: 'Accion 24/7',
    description: 'Películas de acción las 24 horas. Explosiones, tiroteos y adrenalina sin parar.',
    logo: 'https://i.imgur.com/Ot3EdrL.png',
    url: 'https://stmv1.srvstm.com/action24/action24/playlist.m3u8',
    category: 'co-peliculas',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'terror-247',
    name: 'Terror 24/7',
    description: 'Películas de terror y suspenso las 24 horas. Lo mejor del cine de terror.',
    logo: 'https://i.imgur.com/FvqM5ac.png',
    url: 'https://stmv1.srvstm.com/terror/terror/playlist.m3u8',
    category: 'co-peliculas',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'novelas-247',
    name: 'Novelas Clasicas 24/7',
    description: 'Las mejores telenovelas y novelas clásicas latinoamericanas las 24 horas.',
    logo: 'https://i.imgur.com/rbYn7ZW.png',
    url: 'https://stmv1.srvstm.com/tlnovelas/tlnovelas/playlist.m3u8',
    category: 'co-peliculas',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'comedia-247',
    name: 'Comedia 24/7',
    description: 'Películas y series de comedia las 24 horas. Risas garantizadas todo el día.',
    logo: 'https://i.imgur.com/9FywUuY.png',
    url: 'https://stmv1.srvstm.com/comedy/comedy/playlist.m3u8',
    category: 'co-peliculas',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'cine-latino',
    name: 'Cine Latino Free',
    description: 'El mejor cine latinoamericano. Películas en español de todos los géneros.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Cine_Latino_logo.png',
    url: 'https://stream.ads.ottera.tv/playlist.m3u8?network_id=395',
    category: 'co-peliculas',
    language: 'es',
    country: 'LATAM',
  },
  {
    id: 'retro-plus-movies',
    name: 'Retro Plus Movies',
    description: 'Cine clásico y películas retro. Los grandes éxitos de la época dorada del cine.',
    logo: 'https://i.imgur.com/nbtQmU7.png',
    url: 'https://stream.ichibantv.net:3713/hybrid/play.m3u8',
    category: 'co-peliculas',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'veplus',
    name: 'VePlus',
    description: 'Canal de series y novelas. Programación variada de entretenimiento en español.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a5/Venus_TV_logo.png',
    url: 'https://ott.streann.com/loadbalancer/services/PlayMedia/playlist.m3u8?station=veplus1',
    category: 'co-peliculas',
    language: 'es',
    country: 'LATAM',
  },
  {
    id: 'memorias-tv-series',
    name: 'Memorias TV Series',
    description: 'Canales temáticos con series clásicas y contemporáneas las 24 horas.',
    logo: 'https://i.imgur.com/ohCSMhY.png',
    url: 'https://video.xtrematv.com:3633/live/memoriasserieslive.m3u8',
    category: 'co-peliculas',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'memorias-tv-toons',
    name: 'Memorias TV Toons',
    description: 'Animación y caricaturas clásicas. Los mejores cartoons de todos los tiempos.',
    logo: 'https://i.imgur.com/2fiiNCz.png',
    url: 'https://video.xtrematv.com:3812/live/memoriastoonslive.m3u8',
    category: 'co-peliculas',
    language: 'es',
    country: 'CO',
  },

  // ╔═══════════════════════════════════════════════════════════════════╗
  // ║  COLOMBIA - INFANTILES                                           ║
  // ╚═══════════════════════════════════════════════════════════════════╝
  {
    id: 'disney-latam',
    name: 'Disney Channel Latam',
    description: 'Canal infantil con series y películas de Disney. Programación para toda la familia.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/f/ff/2024_Disney_Channel_text_logo.svg',
    url: 'http://201.217.246.42:44310/Live/3fcb6e26785fd8d415571b26dc3cf5d3/local-32.playlist.m3u8',
    category: 'co-infantil',
    language: 'es',
    country: 'LATAM',
  },
  {
    id: 'eureka',
    name: 'Eureka',
    description: 'Canal educativo infantil colombiano. Aprende jugando con los mejores contenidos.',
    logo: 'https://i.imgur.com/WgnZPol.png',
    url: 'https://mdstrm.com/live-stream-playlist/6952e02d19eabace52e2885f.m3u8',
    category: 'co-infantil',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'toonizaki',
    name: 'Toonizaki',
    description: 'Animación y anime para niños y jóvenes. Los mejores dibujos animados del momento.',
    logo: 'https://i.imgur.com/C9Yv6Qo.png',
    url: 'https://stream.ichibantv.net:3351/hybrid/play.m3u8',
    category: 'co-infantil',
    language: 'es',
    country: 'LATAM',
  },

  // ╔═══════════════════════════════════════════════════════════════════╗
  // ║  COLOMBIA - ENTRETENIMIENTO                                      ║
  // ╚═══════════════════════════════════════════════════════════════════╝
  {
    id: 'comedy-central-latam',
    name: 'Comedy Central Latam',
    description: 'Stand-up, series de comedia y humor. Los mejores comediantes del mundo.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Comedy_Central_2018.svg/200px-Comedy_Central_2018.svg.png',
    url: 'http://201.217.246.42:44310/Live/3fcb6e26785fd8d415571b26dc3cf5d3/local-60.playlist.m3u8',
    category: 'co-entretenimiento',
    language: 'es',
    country: 'LATAM',
  },
  {
    id: 'mtv-latam',
    name: 'MTV Latinoamérica',
    description: 'Música, cultura pop, reality shows y series. El canal de la juventud global.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/MTV_2021_%28brand_version%29.svg/200px-MTV_2021_%28brand_version%29.svg.png',
    url: 'http://201.217.246.42:44310/Live/3fcb6e26785fd8d415571b26dc3cf5d3/local-50.playlist.m3u8',
    category: 'co-entretenimiento',
    language: 'es',
    country: 'LATAM',
  },
  {
    id: 'teve-colombia',
    name: 'TeveColombia',
    description: 'Canal de entretenimiento colombiano. Magazine, farándula y programas de variedades.',
    logo: 'https://i.imgur.com/vPwiJTw.png',
    url: 'https://cloud6.livescast.com:3900/live/tevecolombialive.m3u8',
    category: 'co-entretenimiento',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'mci-television',
    name: 'MCI Televisión',
    description: 'Canal familiar con películas, series y entretenimiento para toda la familia.',
    logo: 'https://i.imgur.com/I0eGYI0.png',
    url: 'https://video.ejeserver.com/live/mcitelevision.m3u8',
    category: 'co-entretenimiento',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'canal-nets',
    name: 'Canal Nets',
    description: 'Canal de entretenimiento colombiano con programación variada y original.',
    logo: 'https://i.imgur.com/edaAexc.png',
    url: 'https://movil.ejeserver.com/live/nets.m3u8',
    category: 'co-entretenimiento',
    language: 'es',
    country: 'CO',
  },

  // ╔═══════════════════════════════════════════════════════════════════╗
  // ║  COLOMBIA - RELIGIOSOS                                           ║
  // ╚═══════════════════════════════════════════════════════════════════╝
  {
    id: 'cristovision',
    name: 'Cristovision',
    description: 'Canal católico colombiano. Misa en vivo, rosario y programación religiosa.',
    logo: 'https://i.imgur.com/XIhCUY9.png',
    url: 'https://5fc584f3f19c9.streamlock.net/cristovision/videocristovision/playlist.m3u8',
    category: 'co-religiosos',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'cmb-television',
    name: 'CMB Television',
    description: 'Canal religioso cristiano con programación espiritual y música de alabanza.',
    logo: 'https://i.imgur.com/akGKPsk.png',
    url: 'https://cdn1.cmbcolombia.tv/bethesda/video.m3u8',
    category: 'co-religiosos',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'bendicion-channel',
    name: 'Bendicion Channel',
    description: 'Canal religioso con prédicas, cultos y programación espiritual las 24 horas.',
    logo: 'https://i.imgur.com/yKzV7m7.png',
    url: 'https://s.emisoras.tv:8081/bendicionchannel/index.m3u8',
    category: 'co-religiosos',
    language: 'es',
    country: 'CO',
  },
  {
    id: 'tele-vid',
    name: 'Tele Vid',
    description: 'Canal religioso colombiano con misas, celebraciones y contenido espiritual.',
    logo: 'https://i.imgur.com/OZ4kiXP.png',
    url: 'https://liveingesta118.cdnmedia.tv/televidtvlive/smil:rtmp01.smil/playlist.m3u8',
    category: 'co-religiosos',
    language: 'es',
    country: 'CO',
  },

  // ╔═══════════════════════════════════════════════════════════════════╗
  // ║  LATAM - CANALES LATINOS                                         ║
  // ╚═══════════════════════════════════════════════════════════════════╝
  {
    id: 'azteca-uno',
    name: 'Azteca Uno',
    description: 'Canal mexicano de televisión abierta. Noticias, novelas y entretenimiento.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/3/36/Azteca_Uno_logo.svg',
    url: 'https://mdstrm.com/live-stream-playlist/5a7b1e63cc2e28072f76e3a3.m3u8',
    category: 'latam',
    language: 'es',
    country: 'MX',
  },
  {
    id: 'tv-publica-ar',
    name: 'TV Pública Argentina',
    description: 'Canal público de Argentina. Noticias, cultura, deportes y entretenimiento.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/7/75/TV_Publica_Argentina_logo.png',
    url: 'https://raw.githubusercontent.com/iptv-org/iptv/master/streams/ar/tvpublica.m3u8',
    category: 'latam',
    language: 'es',
    country: 'AR',
  },
  {
    id: 'rts-ecuador',
    name: 'RTS Ecuador',
    description: 'Canal ecuatoriano con noticias, entretenimiento y programación cultural.',
    logo: 'https://i.imgur.com/eq3yO2p.png',
    url: 'https://api.streamyes.com/live/rts/playlist.m3u8',
    category: 'latam',
    language: 'es',
    country: 'EC',
  },
  {
    id: 'vida-tv',
    name: 'Vida TV',
    description: 'Canal de series y novelas latinoamericanas. Programación familiar 24/7.',
    logo: 'https://i.imgur.com/wSrD8Ix.png',
    url: 'https://dacastmmd.mmdlive.lldns.net/dacastmmd/98bfd59bbd1d4d42b507995702d00278/index.m3u8',
    category: 'latam',
    language: 'es',
    country: 'LATAM',
  },

  // ╔═══════════════════════════════════════════════════════════════════╗
  // ║  INTERNACIONAL - NOTICIAS                                        ║
  // ╚═══════════════════════════════════════════════════════════════════╝
  {
    id: 'france24-en',
    name: 'France 24 English',
    description: 'Noticias internacionales en inglés las 24 horas. Cobertura global desde París.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/France_24_logo.svg/200px-France_24_logo.svg.png',
    url: 'https://stream.france24.com/F24_EN_HI_HLS/live_web.m3u8',
    category: 'news',
    language: 'en',
    country: 'FR',
  },
  {
    id: 'france24-es',
    name: 'France 24 Español',
    description: 'Noticias internacionales en español las 24 horas. Perspectiva global desde París.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/France_24_logo.svg/200px-France_24_logo.svg.png',
    url: 'https://stream.france24.com/F24_ES_HI_HLS/live_web.m3u8',
    category: 'news',
    language: 'es',
    country: 'FR',
  },
  {
    id: 'dw-english',
    name: 'DW English',
    description: 'Deutsche Welle en inglés. Noticias, documentales y reportajes desde Alemania.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Deutsche_Welle_symbol_2012.svg/200px-Deutsche_Welle_symbol_2012.svg.png',
    url: 'https://dwamdstream104.akamaized.net/hls/live/2015530/dwstream104/index.m3u8',
    category: 'news',
    language: 'en',
    country: 'DE',
  },
  {
    id: 'dw-espanol',
    name: 'DW Español',
    description: 'Deutsche Welle en español. Noticias internacionales y cultura desde Alemania.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Deutsche_Welle_symbol_2012.svg/200px-Deutsche_Welle_symbol_2012.svg.png',
    url: 'https://dwamdstream100.akamaized.net/hls/live/2015525/dwstream100/stream03/streamPlaylist.m3u8',
    category: 'news',
    language: 'es',
    country: 'DE',
  },
  {
    id: 'euronews',
    name: 'Euronews',
    description: 'Canal de noticias europeo. Cobertura de toda Europa y el mundo en varios idiomas.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Euronews_2023_logo.svg/200px-Euronews_2023_logo.svg.png',
    url: 'https://rakuten-euronews-es-1-es.samsung.wurl.tv/playlist.m3u8',
    category: 'news',
    language: 'es',
    country: 'EU',
  },
  {
    id: 'abc-news',
    name: 'ABC News Live',
    description: 'Canal de noticias en vivo de ABC News. Cobertura 24/7 desde Estados Unidos.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/ABC_News_logo.svg/200px-ABC_News_logo.svg.png',
    url: 'https://content.uplynk.com/channel/3324f2467c414329b3b0cc5cd987b6be.m3u8',
    category: 'news',
    language: 'en',
    country: 'US',
  },

  // ╔═══════════════════════════════════════════════════════════════════╗
  // ║  INTERNACIONAL - DOCUMENTALES Y CIENCIA                          ║
  // ╚═══════════════════════════════════════════════════════════════════╝
  {
    id: 'nasa-tv',
    name: 'NASA TV',
    description: 'Transmisiones en vivo de la NASA. Lanzamientos, paseos espaciales y cobertura de misiones.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/NASA_logo.svg/200px-NASA_logo.svg.png',
    url: 'https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-HLS/master.m3u8',
    category: 'documentary',
    language: 'en',
    country: 'US',
  },
  {
    id: 'nasa-media',
    name: 'NASA Media Channel',
    description: 'Canal de medios de la NASA. Documentales, entrevistas y cobertura especial de misiones.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/NASA_logo.svg/200px-NASA_logo.svg.png',
    url: 'https://ntv2.akamaized.net/hls/live/2013923/NASA-NTV2-HLS/master.m3u8',
    category: 'documentary',
    language: 'en',
    country: 'US',
  },
  {
    id: 'smithsonian',
    name: 'Smithsonian Channel',
    description: 'Documentales sobre ciencia, historia, naturaleza y cultura. Programación premium.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Smithsonian_Channel_logo.svg/200px-Smithsonian_Channel_logo.svg.png',
    url: 'https://smithsonianlichn.akamaized.net/hls/live/2028241/sichannel/master.m3u8',
    category: 'documentary',
    language: 'en',
    country: 'US',
  },

  // ╔═══════════════════════════════════════════════════════════════════╗
  // ║  INTERNACIONAL - DEPORTES                                        ║
  // ╚═══════════════════════════════════════════════════════════════════╝
  {
    id: 'bein-sports-xtra',
    name: 'beIN Sports XTRA',
    description: 'Canal de deportes con programación variada: fútbol, tenis, baloncesto y más.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/BeIN_Sports_logo.svg/200px-BeIN_Sports_logo.svg.png',
    url: 'https://bfrench.akamaized.net/hls/live/2032676/bfmtv2/index.m3u8',
    category: 'sports',
    language: 'en',
    country: 'US',
  },
  {
    id: 'stadium-sports',
    name: 'Stadium Sports',
    description: 'Deportes universitarios y eventos especiales en vivo. Fútbol americano y baloncesto NCAA.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Stadium_logo.svg/200px-Stadium_logo.svg.png',
    url: 'https://content.uplynk.com/channel/7689a937067e4defa59f23e56f9c76f1.m3u8',
    category: 'sports',
    language: 'en',
    country: 'US',
  },

  // ╔═══════════════════════════════════════════════════════════════════╗
  // ║  INTERNACIONAL - MUSICA                                          ║
  // ╚═══════════════════════════════════════════════════════════════════╝
  {
    id: 'music-choice',
    name: 'Music Choice',
    description: 'Canales de música las 24 horas. Pop, rock, hip-hop, latin y más géneros.',
    logo: 'https://picsum.photos/seed/music-choice/200/200',
    url: 'https://music-choice.akamaized.net/hls/live/2097871/MCHRNB/master.m3u8',
    category: 'music',
    language: 'en',
    country: 'US',
  },
  {
    id: 'hit-tv',
    name: 'HIT TV Music',
    description: 'Los mejores videos musicales del momento. Pop, reggaetón, y éxitos latinos.',
    logo: 'https://picsum.photos/seed/hit-tv/200/200',
    url: 'https://tvtmspplive.akamaized.net/hls/live/2047811/ALHD/master.m3u8',
    category: 'music',
    language: 'es',
    country: 'ES',
  },
  {
    id: 'vibra-music',
    name: 'Vibra Music',
    description: 'Música latina tropical y urbana. Reggaetón, salsa, bachata y más.',
    logo: 'https://i.imgur.com/2mht4Jp.png',
    url: 'https://stream.ichibantv.net:3512/live/playlist.m3u8',
    category: 'music',
    language: 'es',
    country: 'LATAM',
  },
];

export const LIVE_TV_CATEGORIES = [
  { id: 'all', name: 'Todos', icon: '📺' },
  { id: 'co-nacional', name: 'Colombia Nacionales', icon: '🇨🇴' },
  { id: 'co-regional', name: 'Colombia Regionales', icon: '🗺️' },
  { id: 'co-deportes', name: 'Deportes', icon: '⚽' },
  { id: 'co-noticias', name: 'Noticias CO', icon: '📰' },
  { id: 'co-musica', name: 'Música CO', icon: '🎵' },
  { id: 'co-peliculas', name: 'Películas/Series', icon: '🎬' },
  { id: 'co-infantil', name: 'Infantiles', icon: '👶' },
  { id: 'co-entretenimiento', name: 'Entretenimiento', icon: '🎭' },
  { id: 'co-religiosos', name: 'Religiosos', icon: '⛪' },
  { id: 'latam', name: 'Latinoamérica', icon: '🌎' },
  { id: 'news', name: 'Noticias Intl', icon: '🌐' },
  { id: 'documentary', name: 'Documentales', icon: '🔬' },
  { id: 'sports', name: 'Deportes Intl', icon: '🏆' },
  { id: 'music', name: 'Música Intl', icon: '🎧' },
];

export function getChannelsByCategory(category: string): LiveTVChannel[] {
  if (category === 'all') return LIVE_TV_CHANNELS;
  return LIVE_TV_CHANNELS.filter((ch) => ch.category === category);
}
