import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const movies = [
  // Featured Movies
  {
    title: "El Último Horizonte",
    description: "Un viaje épico a través de los paisajes más impresionantes de Latinoamérica, donde un grupo de aventureros descubre secretos ancestrales ocultos en las profundidades de la selva amazónica. Una historia de coraje, amistad y descubrimiento que cambiará sus vidas para siempre.",
    posterUrl: "https://picsum.photos/seed/movie1/400/600",
    backdropUrl: "https://picsum.photos/seed/movie1bg/1920/1080",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    year: 2025,
    duration: "2h 15min",
    rating: 8.7,
    genre: "Aventura",
    category: "peliculas",
    featured: true,
    trending: true,
  },
  {
    title: "Sombras del Pasado",
    description: "Un thriller psicológico que sigue a una detective que debe resolver una serie de crímenes misteriosos en las calles de Buenos Aires. Cada pista la lleva más profundamente a un laberinto de conspiraciones que amenazan con destruir todo lo que conoce.",
    posterUrl: "https://picsum.photos/seed/movie2/400/600",
    backdropUrl: "https://picsum.photos/seed/movie2bg/1920/1080",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    year: 2025,
    duration: "1h 58min",
    rating: 8.3,
    genre: "Thriller",
    category: "peliculas",
    featured: true,
    trending: true,
  },
  {
    title: "Corazón de Fuego",
    description: "La historia real de un bombero que arriesga todo para salvar a su equipo atrapado en un incendio forestal en Chile. Una historia inspiradora de valentía y sacrificio humano en medio del caos.",
    posterUrl: "https://picsum.photos/seed/movie3/400/600",
    backdropUrl: "https://picsum.photos/seed/movie3bg/1920/1080",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    year: 2024,
    duration: "2h 05min",
    rating: 9.1,
    genre: "Drama",
    category: "peliculas",
    featured: true,
    trending: false,
  },
  {
    title: "La Rebelión",
    description: "En un futuro cercano, un grupo de jóvenes hackers descubre una conspiración global que amenaza la libertad de internet. Deberán unir fuerzas para exponer la verdad antes de que sea demasiado tarde.",
    posterUrl: "https://picsum.photos/seed/movie4/400/600",
    backdropUrl: "https://picsum.photos/seed/movie4bg/1920/1080",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    year: 2025,
    duration: "2h 22min",
    rating: 7.9,
    genre: "Ciencia Ficción",
    category: "peliculas",
    featured: false,
    trending: true,
  },
  {
    title: "Ritmo Salvaje",
    description: "Un documental vibrante sobre la cultura musical urbana en Colombia, México y Argentina. Desde el reggaetón hasta el hip-hop latino, explore cómo la música está uniendo a toda una generación.",
    posterUrl: "https://picsum.photos/seed/movie5/400/600",
    backdropUrl: "https://picsum.photos/seed/movie5bg/1920/1080",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    year: 2024,
    duration: "1h 45min",
    rating: 8.5,
    genre: "Documental",
    category: "peliculas",
    featured: false,
    trending: true,
  },
  // Series
  {
    title: "Frontera Oscura",
    description: "Temporada 1. En la frontera entre México y Estados Unidos, un agente de la DEA y una periodista descubren una red de narcotráfico que conecta a los más altos niveles del poder político. 10 episodios de suspenso intenso.",
    posterUrl: "https://picsum.photos/seed/series1/400/600",
    backdropUrl: "https://picsum.photos/seed/series1bg/1920/1080",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    year: 2025,
    duration: "10 Episodios",
    rating: 9.2,
    genre: "Drama",
    category: "series",
    featured: true,
    trending: true,
  },
  {
    title: "Cocina Latina",
    description: "Temporada 3. El chef más famoso de Latinoamérica viaja por Perú, Brasil y Ecuador descubriendo los sabores más auténticos del continente. Cada episodio es una fiesta para los sentidos.",
    posterUrl: "https://picsum.photos/seed/series2/400/600",
    backdropUrl: "https://picsum.photos/seed/series2bg/1920/1080",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    year: 2025,
    duration: "12 Episodios",
    rating: 8.8,
    genre: "Reality",
    category: "series",
    featured: false,
    trending: true,
  },
  {
    title: "Código Cero",
    description: "Temporada 2. Un equipo de ciberseguridad debe proteger a América Latina de un ataque masivo de hackers. Tecnología, espionaje y acción en cada episodio de esta serie de alta tensión.",
    posterUrl: "https://picsum.photos/seed/series3/400/600",
    backdropUrl: "https://picsum.photos/seed/series3bg/1920/1080",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    year: 2024,
    duration: "8 Episodios",
    rating: 8.6,
    genre: "Acción",
    category: "series",
    featured: false,
    trending: false,
  },
  {
    title: "Amores Cruzados",
    description: "Temporada 4. Tres parejas de diferentes países de Latinoamérica se entrelazan en una historia de amor, desamor y segundas oportunidades. Grabada en Bogotá, Ciudad de México y Santiago de Chile.",
    posterUrl: "https://picsum.photos/seed/series4/400/600",
    backdropUrl: "https://picsum.photos/seed/series4bg/1920/1080",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
    year: 2025,
    duration: "16 Episodios",
    rating: 7.8,
    genre: "Romance",
    category: "series",
    featured: false,
    trending: true,
  },
  {
    title: "Historia Viva",
    description: "Temporada 1. Un documental dramatizado que recrea los momentos más importantes de la historia latinoamericana. Desde la independencia hasta la era moderna, con actores de primer nivel.",
    posterUrl: "https://picsum.photos/seed/series5/400/600",
    backdropUrl: "https://picsum.photos/seed/series5bg/1920/1080",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    year: 2024,
    duration: "10 Episodios",
    rating: 9.0,
    genre: "Documental",
    category: "series",
    featured: false,
    trending: false,
  },
  // Live Channels
  {
    title: "Deportes Total",
    description: "Transmisión en vivo de los mejores eventos deportivos de Latinoamérica: fútbol, boxeo, béisbol y mucho más. Cobertura completa 24/7.",
    posterUrl: "https://picsum.photos/seed/live1/400/600",
    backdropUrl: "https://picsum.photos/seed/live1bg/1920/1080",
    year: 2025,
    duration: "24/7",
    rating: 8.4,
    genre: "Deportes",
    category: "deportes",
    isLive: true,
    featured: true,
    trending: true,
  },
  {
    title: "Noticias del Mundo",
    description: "Canal de noticias en vivo con cobertura en tiempo real de los eventos más importantes de América Latina y el mundo. Análisis, entrevistas y reportajes especiales.",
    posterUrl: "https://picsum.photos/seed/live2/400/600",
    backdropUrl: "https://picsum.photos/seed/live2bg/1920/1080",
    year: 2025,
    duration: "24/7",
    rating: 7.6,
    genre: "Noticias",
    category: "tv",
    isLive: true,
    featured: false,
    trending: false,
  },
  {
    title: "Música 24/7",
    description: "Los mejores videos musicales, conciertos en vivo y entrevistas con los artistas más populares del momento. Reggaetón, pop, rock y más en un solo canal.",
    posterUrl: "https://picsum.photos/seed/live3/400/600",
    backdropUrl: "https://picsum.photos/seed/live3bg/1920/1080",
    year: 2025,
    duration: "24/7",
    rating: 8.1,
    genre: "Música",
    category: "tv",
    isLive: true,
    featured: false,
    trending: true,
  },
  {
    title: "Fútbol Premier",
    description: "Todos los partidos de la liga en vivo con comentarios en español. Pre-partidos, medio tiempo y post-partidos con análisis de expertos.",
    posterUrl: "https://picsum.photos/seed/sport1/400/600",
    backdropUrl: "https://picsum.photos/seed/sport1bg/1920/1080",
    year: 2025,
    duration: "En Vivo",
    rating: 9.3,
    genre: "Fútbol",
    category: "deportes",
    isLive: true,
    featured: false,
    trending: true,
  },
  {
    title: "Lucha Libre Elite",
    description: "Los mejores eventos de lucha libre y MMA transmitidos en vivo. Noches de acción con los campeones más grandes del momento.",
    posterUrl: "https://picsum.photos/seed/sport2/400/600",
    backdropUrl: "https://picsum.photos/seed/sport2bg/1920/1080",
    year: 2025,
    duration: "En Vivo",
    rating: 8.7,
    genre: "Lucha",
    category: "deportes",
    isLive: true,
    featured: false,
    trending: false,
  },
  // More Movies
  {
    title: "La Herencia Maldita",
    description: "Cuando una familia adinerada reúne a todos sus miembros en una mansión aislada en la Patagonia, secretos oscuros comienzan a salir a la luz. Un misterio familiar que pondrá a prueba los lazos de sangre.",
    posterUrl: "https://picsum.photos/seed/movie6/400/600",
    backdropUrl: "https://picsum.photos/seed/movie6bg/1920/1080",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
    year: 2024,
    duration: "1h 52min",
    rating: 7.5,
    genre: "Misterio",
    category: "peliculas",
    featured: false,
    trending: false,
  },
  {
    title: "Comedia en Vivo",
    description: "Los mejores comediantes de stand-up de Latinoamérica en un especial grabado en Ciudad de México. Risas garantizadas con los jokes más virales del momento.",
    posterUrl: "https://picsum.photos/seed/movie7/400/600",
    backdropUrl: "https://picsum.photos/seed/movie7bg/1920/1080",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
    year: 2025,
    duration: "1h 30min",
    rating: 8.0,
    genre: "Comedia",
    category: "peliculas",
    featured: false,
    trending: true,
  },
  {
    title: "Almas Perdidas",
    description: "Un drama conmovedor sobre tres inmigrantes latinoamericanos que buscan una nueva vida en Europa. Una historia de esperanza, resiliencia y los lazos que nos unen más allá de las fronteras.",
    posterUrl: "https://picsum.photos/seed/movie8/400/600",
    backdropUrl: "https://picsum.photos/seed/movie8bg/1920/1080",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
    year: 2024,
    duration: "2h 10min",
    rating: 8.9,
    genre: "Drama",
    category: "peliculas",
    featured: false,
    trending: false,
  },
  {
    title: "El Laberinto Digital",
    description: "Un thriller tecnológico donde una inteligencia artificial desarrollada en Brasil comienza a tomar decisiones propias, poniendo en riesgo a toda la humanidad. ¿Podrán detenerla a tiempo?",
    posterUrl: "https://picsum.photos/seed/movie9/400/600",
    backdropUrl: "https://picsum.photos/seed/movie9bg/1920/1080",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    year: 2025,
    duration: "2h 08min",
    rating: 8.2,
    genre: "Ciencia Ficción",
    category: "peliculas",
    featured: false,
    trending: true,
  },
  {
    title: "Sabor a Casa",
    description: "Una comedia romántica que sigue a una chef mexicana que regresa a su pueblo natal para salvar el restaurante familiar. Entre recetas tradicionales y un amor inesperado, descubrirá que no hay lugar como el hogar.",
    posterUrl: "https://picsum.photos/seed/movie10/400/600",
    backdropUrl: "https://picsum.photos/seed/movie10bg/1920/1080",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    year: 2025,
    duration: "1h 48min",
    rating: 7.7,
    genre: "Comedia",
    category: "peliculas",
    featured: false,
    trending: false,
  },
  // More Series
  {
    title: "Agentes Secretos",
    description: "Temporada 1. Un thriller de espionaje ambientado durante la Guerra Fría en Latinoamérica. Cinco agentes de diferentes países deben colaborar para evitar una catástrofe nuclear.",
    posterUrl: "https://picsum.photos/seed/series6/400/600",
    backdropUrl: "https://picsum.photos/seed/series6bg/1920/1080",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    year: 2025,
    duration: "10 Episodios",
    rating: 8.4,
    genre: "Acción",
    category: "series",
    featured: false,
    trending: false,
  },
  {
    title: "Médicos de Emergencia",
    description: "Temporada 3. La vida en el hospital más grande de São Paulo vista a través de los ojos de los médicos y enfermeras que luchan cada día por salvar vidas.",
    posterUrl: "https://picsum.photos/seed/series7/400/600",
    backdropUrl: "https://picsum.photos/seed/series7bg/1920/1080",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    year: 2024,
    duration: "14 Episodios",
    rating: 8.1,
    genre: "Drama",
    category: "series",
    featured: false,
    trending: true,
  },
  // TV Channels
  {
    title: "Cartoon Planet",
    description: "El mejor canal de animación para toda la familia. Dibujos clásicos y nuevos estrenos las 24 horas del día.",
    posterUrl: "https://picsum.photos/seed/tv1/400/600",
    backdropUrl: "https://picsum.photos/seed/tv1bg/1920/1080",
    year: 2025,
    duration: "24/7",
    rating: 7.9,
    genre: "Animación",
    category: "tv",
    isLive: true,
    featured: false,
    trending: false,
  },
  {
    title: "Cine Clásico",
    description: "Los grandes clásicos del cine latinoamericano y mundial. Películas que marcaron una época, disponibles las 24 horas.",
    posterUrl: "https://picsum.photos/seed/tv2/400/600",
    backdropUrl: "https://picsum.photos/seed/tv2bg/1920/1080",
    year: 2025,
    duration: "24/7",
    rating: 8.3,
    genre: "Cine",
    category: "tv",
    isLive: true,
    featured: false,
    trending: false,
  },
];

async function main() {
  console.log('🌱 Seeding database...');

  // Clear existing data
  await prisma.favorite.deleteMany();
  await prisma.movie.deleteMany();
  await prisma.user.deleteMany();

  // Create a demo user
  const demoUser = await prisma.user.create({
    data: {
      email: 'demo@xuperstream.com',
      name: 'Usuario Demo',
      password: 'demo123',
      plan: 'vip',
    },
  });

  // Create movies
  for (const movie of movies) {
    await prisma.movie.create({ data: movie });
  }

  // Add some favorites for the demo user
  const firstMovies = await prisma.movie.findMany({ take: 5 });
  for (const movie of firstMovies) {
    await prisma.favorite.create({
      data: {
        userId: demoUser.id,
        movieId: movie.id,
      },
    });
  }

  console.log(`✅ Seeded ${movies.length} movies`);
  console.log(`✅ Created demo user: ${demoUser.email}`);
  console.log(`✅ Added ${firstMovies.length} favorites`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
